ansible-community/antsibull-nox

- changelogs/fragments/1.yml
- pyproject.toml
- src/antsibull_nox/collection.py
- src/antsibull_nox/sessions.py
~~This is currently blocked by https://github.com/pylint-dev/pylint/issues/10278.~~
> Improve pylint and mypy linting by not requiring directory structure outside of repository

- README.md
- REUSE.toml
- Add REUSE tags to REUSE.toml, the only file (ironically) lacking them.
- Remove the note from the end of README.md about changelog fragments not being REUSE compliant, because the configs in REUSE.toml applies GPL-3.0-or-later to all fragments.
> Full REUSE compliance

- changelogs/fragments/22-adjacent-collections.yml
- src/antsibull_nox/collection.py
- tests/unit/test_collection.py
> Find dependent collections in ../<namespace>.<name> when CWD is not part of ansible_collections tree

- docs/reference.md
- src/antsibull_nox/paths.py
- src/antsibull_nox/sessions.py
This is necessary for antsibull-docs lint-session-docs, as ansible-doc doesn't like to be run in a nested `ansible_collections` tree and will spuriously fail in some situations. (I haven't been able to completely figure out when...)
Ref: https://github.com/ansible/ansible/issues/84909
> Allow to have collection root outside of .nox session directory

- changelogs/fragments/31-descriptions.yml
- src/antsibull_nox/sessions.py
The `nox -l` output for community.dns will look like this:
```
* lint -> Meta session for triggering the following sessions: formatters, codeqa, and typing
* formatters -> Run code formatters: isort and black
* codeqa -> Run code QA: flake8 and pylint
* typing -> Run type checker: mypy
* docs-check -> Run 'antsibull-docs lint-collection-docs'
* license-check -> Run license checkers: reuse and license-check (ensure GPLv3+ for plugins)
* extra-checks -> Run extra checkers: no-unwanted-files (checks for unwanted files in plugins/) and action-groups (validate action groups)
* build-import-check -> Run build and import checkers: build-collection and galaxy-importer (test whether Galaxy will import built collection)
* update-docs-fragments -> Update/check auto-generated parts of docs fragments. …
```
> Generate descriptions for sessions

- .pylintrc.automated
- action.yml
- changelogs/fragments/32-ansible-test.yml
- docs/reference.md
- src/antsibull_nox/__init__.py
- src/antsibull_nox/ansible.py
- src/antsibull_nox/paths.py
- src/antsibull_nox/sessions.py
- src/antsibull_nox/utils.py
- tests/needs-network/test_ansible_core.py
- tests/unit/test_ansible.py
- tests/unit/test_utils.py
Adds functions to add ansible-test sessions.
Fixes #5.
I've tested this with community.dns by adding the following to its `noxfile.py` (see https://github.com/ansible-collections/community.dns/pull/255):
```python
antsibull_nox.add_all_ansible_test_sanity_test_sessions(include_devel=True)
antsibull_nox.add_all_ansible_test_unit_test_sessions(include_devel=True)
antsibull_nox.add_ansible_test_integration_sessions_default_container(
core_python_versions={
"2.14": ["2.7", "3.5", "3.9"],
"2.15": ["3.7"],
"2.16": ["2.7", "3.6", "3.11"],
"2.17": ["3.7", "3.12"],
"2.18": ["3.8", "3.13"],
},
include_devel=True,
)
```
This basically runs everything that's also run by https://github.com/ansible-collections/community.dns/blob/main/.github/workflows/ansible-test.yml.
> Integrate ansible-test; allow to create CI matrixes for it

- src/antsibull_nox/sessions.py
This worked previously because of the way the actual function is defined, but that's an implementation detail. The typing overloads state that this should be called like a function decorator — either plain `@nox.session` (equivalent to `nox.session(func)`) or with arguments, `@nox.section(name=...)` (equivalent to `nox.session(name=...)(func)`).
> sessions: fix type errors when calling nox.session

- changelogs/fragments/32-ansible-test.yml
- docs/reference.md
- src/antsibull_nox/sessions.py
This is needed to rebase https://github.com/ansible-collections/community.dns/pull/246.
> Allow to add specific branches for ansible-core to ansible-test sessions

- .github/workflows/reusable-nox-matrix.yml
- changelogs/fragments/37-shared-workflow.yml
- docs/nox-in-ci.md
These are no longer needed since antsibull-nox can install the dependencies by itself.
> Remove 'extra-collections-*' parameters from shared workflow

- action.yml
- changelogs/fragments/51-use-installed.yml
- docs/getting-started.md
- src/antsibull_nox/collection/search.py
Currently the community.dns unit tests fail. For `devel`, they need a DT compatible version of `community.library_inventory_filtering_v1`, but GitHub's default image has an older Ansible release installed, and antsibull-nox uses its `community.library_inventory_filtering_v1` instead of installing that collection from Git.
For that reason I generally disabled using installed collections in the GHA action by providing an environment variable to disable that, and using that one in the GH Action.
> Do not use installed collections if environment variable is set

- changelogs/fragments/46-install-missing.yml
- src/antsibull_nox/collection/install.py
https://github.com/felixfontein/ansible-acme/pull/93 fails because of this.
> Fix installation of collection pre-releases

- .github/workflows/reusable-nox-matrix.yml
- changelogs/fragments/37-shared-workflow.yml
The directory structure isn't needed.
Also if we ever need the namespace/name at some point, we can fetch it from galaxy.yml during the first step.
> Remove collection namespace and name parameter from shared workflow

- changelogs/fragments/56-config-lint.yml
- docs/config-file.md
- pyproject.toml
- src/antsibull_nox/__init__.py
- src/antsibull_nox/_pydantic.py
- src/antsibull_nox/cli.py
- src/antsibull_nox/config.py
- src/antsibull_nox/data/antsibull-nox-lint-config.py
- src/antsibull_nox/interpret_config.py
- src/antsibull_nox/lint_config.py
- src/antsibull_nox/sessions/lint.py
Both as a CLI (which can also print nicer errors if the config file cannot be loaded) and a subsession of `lint`.
> Add configuration linter

- changelogs/fragments/59-extra-code-black.yml
- src/antsibull_nox/sessions/lint.py
This caused `update-docs-fragments.py` not being reformatted with black in community.dns.
> Forgot extra_code_files when run_black_modules=false

- action.yml
This will hopefully remedy some mixups produced by GitHub Actions which causes collapsible groups for Galaxy importer output to not work.
> GHA: redirect stderr to stdout

- docs/config-file.md
mkdocs/python-markdown requires 4-space indentation.
> docs config-file: fix nested list indentation

- changelogs/fragments/68-yamllint-return.yml
- src/antsibull_nox/data/plugin-yamllint.py
Right now `RETURN = """ # """` causes YAML linting errors since there's a trailing space in ` # `. Also if you configure that plugin docs should start with a `---`, it will complain about `#` and ` # `. So we handle these two contents specially and simply not run them through yamllint.
> Ignore special RETURN values

- changelogs/fragments/68-yamllint-return.yml
- changelogs/fragments/71-yamllint-return.yml
- changelogs/fragments/72-yamllint-config.yml
- pyproject.toml
- src/antsibull_nox/data/file-yamllint.py
- src/antsibull_nox/data/plugin-yamllint.py
- src/antsibull_nox/sessions/lint.py
This is a breaking change in the sense that it no longer uses the user's global yamllint config, if no explicit config file is passed. I've classified this as a bugfix though since that's not helpful behavior for a CI tool.
> yamllint: use wrapper script to avoid showing all YAML files in command line, and loading user's global config

- src/antsibull_nox/sessions/ansible_test.py
There's a bug (https://github.com/ansible/ansible/issues/85173) in ansible-test's command line handling that can cause problems if `--color` is at the wrong position. This doesn't happen to be the case in our current command lines, but I've still rearranged them so that `--color -v` are always the first two parameters after the ansible-test subcommand.
> Re-arrange ansible-test command lines

- src/antsibull_nox/ansible.py
> Prepare that Python versions supported by milestone differs from the ones supported by devel

- tests/needs-network/test_ansible_core.py
Once `milestone` gets bumped, we need to update the Python information in src/antsibull_nox/ansible.py for `milestone`.
Since the dates for `milestone` updates haven't been announced yet, and they might get delayed for unknown reasons (like forgetting to update it, which happened at least once in the past IIRC), I think it's best to have some automation that tells us that it got updated.
> CI: add test that fails if milestone is updated
