ansible-community/antsibull-nox

- .github/workflows/nox.yml
Ref: https://github.com/ansible-community/antsibull-nox/pull/1#issuecomment-2733939926
> Install nox directly to use the correct Python version

- .github/workflows/test-gh-action.yml
- action.yml
> Improve included GH Action

- .github/workflows/nox.yml
- codecov.yml
- noxfile.py
Simply run the noxfile in tests/test-collection/ (the collection also used for testing the included GH Action).
> Add basic integration tests, improve code coverage upload and config

- action.yml
- changelogs/fragments/14-extra-sessions.yml
- src/antsibull_nox/__init__.py
- src/antsibull_nox/collection.py
- src/antsibull_nox/data/action-groups.py
- src/antsibull_nox/data/license-check.py
- src/antsibull_nox/data/license-check.py.license
- src/antsibull_nox/data/no-unwanted-files.py
- src/antsibull_nox/data_util.py
- src/antsibull_nox/paths.py
- src/antsibull_nox/sessions.py
> Add extra sanity tests

- changelogs/fragments/14-extra-sessions.yml
- changelogs/fragments/15-build-import.yml
- changelogs/fragments/17-build-import.yml
- src/antsibull_nox/__init__.py
- src/antsibull_nox/collection.py
- src/antsibull_nox/paths.py
- src/antsibull_nox/sessions.py
- tests/unit/test_collection.py
> Allow to add session that builds and test imports collection

- src/antsibull_nox/__init__.py
> Re-export everything imported in __init__

- changelogs/fragments/21-default.yml
- src/antsibull_nox/sessions.py
> Allow to not mark sessions as default

- README.md
- docs/getting-started.md
- docs/index.md
- docs/reference.md
- mkdocs.yml
- noxfile.py
~~Work in progress, I have some parts partially filled out, will push more once some parts are more polished.~~
This is now a complete first iteration.
> Write basic documentation

- docs/getting-started.md
- docs/index.md
- docs/introduction.md
- docs/troubleshooting.md
- mkdocs.yml
This change moves details about antsibull-nox to an introduction section and makes getting started more task oriented. Additionally this change breaks troubleshooting into a new, dedicated section.
> docs introduction and getting started

- action.yml
- noxfile.py
- src/antsibull_nox/ansible.py
- src/antsibull_nox/python.py
- src/antsibull_nox/utils.py
- tests/needs-network/test_ansible_core.py
- tests/unit/test_ansible.py
- tests/unit/test_collection.py
- tests/unit/test_python.py
- tests/unit/test_utils.py
> Add version utilities

- .github/workflows/reusable-nox-ansible-test.yml
- changelogs/fragments/37-shared-workflow.yml
- docs/nox-in-ci.md
- docs/reference.md
> Improve shared workflow

- docs/reference.md
- src/antsibull_nox/ansible.py
- src/antsibull_nox/sessions.py
- tests/unit/test_ansible.py
- tests/unit/test_collection.py
- tests/unit/utils.py
> Allow to specify min/max/except versions for ansible-core in range-based sessions

- changelogs/fragments/42-yamllint.yml
- docs/reference.md
- pyproject.toml
- src/antsibull_nox/data/plugin-yamllint.py
- src/antsibull_nox/sessions.py
> Add yamllint session

- src/antsibull_nox/data/action-groups.py
- src/antsibull_nox/data/antsibull_nox_data_util.py
- src/antsibull_nox/data/license-check.py
- src/antsibull_nox/data/no-unwanted-files.py
- src/antsibull_nox/data/plugin-yamllint.py
- src/antsibull_nox/data_util.py
- src/antsibull_nox/sessions.py
yamllint isn't really working in CI yet...
See:
- https://github.com/ansible-collections/community.dns/pull/257
- https://github.com/ansible-collections/community.library_inventory_filtering/pull/32
- https://github.com/felixfontein/ansible-acme/pull/91
> Reorganize data utils

- changelogs/fragments/47-galax-importer-collapse.yml
- src/antsibull_nox/sessions.py
It's always pretty long and mostly not saying anything relevant, so collapse it.
> Collapse Galaxy imorter output on GHA

- changelogs/fragments/50-config.yml
- docs/config-file.md
- docs/getting-started.md
- docs/index.md
- docs/nox-in-ci.md
- mkdocs.yml
- pyproject.toml
- src/antsibull_nox/__init__.py
- src/antsibull_nox/config.py
- src/antsibull_nox/interpret_config.py
- src/antsibull_nox/sessions.py
> Allow to create most sessions from a config file

- src/antsibull_nox/sessions/__init__.py
- src/antsibull_nox/sessions/ansible_lint.py
- src/antsibull_nox/sessions/ansible_test.py
- src/antsibull_nox/sessions/build_import_check.py
- src/antsibull_nox/sessions/collections.py
- src/antsibull_nox/sessions/docs_check.py
- src/antsibull_nox/sessions/extra_checks.py
- src/antsibull_nox/sessions/license_check.py
- src/antsibull_nox/sessions/lint.py
- src/antsibull_nox/sessions/utils.py
> sessions: split out utils and collections modules

- .flake8
- changelogs/fragments/58-init.yml
- docs/getting-started.md
- src/antsibull_nox/cli.py
- src/antsibull_nox/collection/__init__.py
- src/antsibull_nox/collection/search.py
- src/antsibull_nox/init.py
- src/antsibull_nox/lint_config.py
`antsibull-nox init` creates `noxfile.py` and `antsibull-nox.toml` for you. This makes Getting Started a bit simpler.
> Add init tool

- changelogs/fragments/60-fixes.yml
- src/antsibull_nox/data/action-groups.py
Fixing problems found while adding antsibull-nox to more collections.
> Do not fail if there's no action_groups

- changelogs/fragments/61-sanity.yml
- docs/config-file.md
- src/antsibull_nox/config.py
- src/antsibull_nox/interpret_config.py
- src/antsibull_nox/sessions/ansible_test.py
Needed for https://github.com/ansible-collections/community.internal_test_tools/pull/151.
> Add new options for ansible-test sanity sessions

- changelogs/fragments/62-symlinks.yml
- src/antsibull_nox/data/license-check.py
- src/antsibull_nox/data/plugin-yamllint.py
Needed for https://github.com/ansible-collections/community.sops/pull/235.
> Skip symlinks that do not point to files

- .github/workflows/reusable-nox-matrix.yml
- changelogs/fragments/63-workflow.yml
- docs/reference.md
- src/antsibull_nox/sessions/ansible_test.py
Needed for https://github.com/ansible-collections/community.sops/pull/235.
> Improve add_ansible_test_session() and shared workflow

- .github/workflows/reusable-nox-matrix.yml
- changelogs/fragments/64-workflow.yml
Needed for https://github.com/ansible-collections/community.sops/pull/235.
> Allow to disable coverage upload for specific integration test jobs

- changelogs/fragments/65-fix.yml
- src/antsibull_nox/sessions/utils.py
Needed for https://github.com/ansible-collections/community.crypto/pull/861.
> Fix failure when run_reuse=false

- changelogs/fragments/74-ansible-lint-args.yml
- src/antsibull_nox/sessions/ansible_lint.py
Like `nox -Re ansible-lint -- --fix`.
> Allow to pass positional arguments to ansible-lint

- .pylintrc.automated
- changelogs/fragments/75-mypy-pylint-errors.yml
- src/antsibull_nox/sessions/lint.py
Makes working on https://github.com/ansible-collections/community.crypto/pull/885 less painful ;)
> Improve paths in pylint and mypy error output

- changelogs/fragments/76-collection-per-ansible-core-version.yml
- docs/config-file.md
- src/antsibull_nox/ansible.py
- src/antsibull_nox/collection/data.py
- src/antsibull_nox/collection/install.py
- src/antsibull_nox/collection/search.py
- src/antsibull_nox/config.py
- src/antsibull_nox/interpret_config.py
- src/antsibull_nox/sessions/ansible_test.py
- src/antsibull_nox/sessions/collections.py
- tests/unit/test_collection.py
This is now needed since community.crypto's `main` branch no longer supports ansible-core < 2.17.
https://github.com/felixfontein/ansible-acme/pull/98 shows an example.
> Install collections from sources depending on the ansible-core version

- changelogs/fragments/80-action-groups.yml
- src/antsibull_nox/data/action-groups.py
It's currently broken: no errors are reported... :facepalm:
> Fix action group test

- changelogs/fragments/94-avoid-characters.yml
- docs/config-file.md
- src/antsibull_nox/config.py
- src/antsibull_nox/data/avoid-characters.py
- src/antsibull_nox/interpret_config.py
- src/antsibull_nox/sessions/extra_checks.py
> Add avoid-characters extra check

- changelogs/fragments/95-rst-yaml-ansible-output-data.yml
- src/antsibull_nox/data/rst-yamllint.py
> Also yamllint ansible-output-meta directives

- .github/workflows/reusable-nox-matrix.yml
- changelogs/fragments/16-ee-check.yml
- docs/config-file.md
- docs/nox-in-ci.md
- src/antsibull_nox/config.py
- src/antsibull_nox/interpret_config.py
- src/antsibull_nox/sessions/ee_check.py
> EE tests: add more parameters, add EE tests to CI matrix for reusable workflow

- changelogs/fragments/102-devel.yml
- src/antsibull_nox/ansible.py
Ref: https://github.com/ansible/ansible/pull/85576
> Update supported Python versions for ansible-core devel

- changelogs/fragments/109-milestone.yml
- src/antsibull_nox/ansible.py
- tests/needs-network/test_ansible_core.py
> Update supported Python versions for ansible-core milestone

- src/antsibull_nox/ansible.py
Follow-up to #93, which wasn't implemented completely.
> Make it possible to properly distinguish between milestone and devel

- changelogs/fragments/117-vars.yml
- docs/config-file.md
- src/antsibull_nox/config.py
- src/antsibull_nox/interpret_config.py
- src/antsibull_nox/sessions/ansible_test.py
- src/antsibull_nox/sessions/utils.py
Preparation for #114, where I'd like to have a more flexible way of specifying vars than the existing mechanism.
> Add ansible_vars config directive

- action.yml
- changelogs/fragments/120-change-detection.yml
- docs/change-detection.md
- docs/config-file.md
- docs/reference.md
- docs/troubleshooting.md
- mkdocs.yml
- src/antsibull_nox/__init__.py
- src/antsibull_nox/cd.py
- src/antsibull_nox/cli.py
- src/antsibull_nox/config.py
- src/antsibull_nox/sessions/ansible_test.py
- src/antsibull_nox/vcs/__init__.py
- src/antsibull_nox/vcs/factory.py
- src/antsibull_nox/vcs/git.py
- src/antsibull_nox/vcs/utils.py
> Add basic Change Detection support

- .github/workflows/reusable-nox-matrix.yml
- changelogs/fragments/120-change-detection.yml
> Support change detection in the shared workflow

- changelogs/fragments/change-detection.yml
- src/antsibull_nox/sessions/ansible_test.py
> CD: prevent 'changed' integration_config.yml from running all tests

- changelogs/fragments/133-extra-deps.yml
- docs/config-file.md
- src/antsibull_nox/config.py
- src/antsibull_nox/interpret_config.py
- src/antsibull_nox/sessions/ansible_lint.py
- src/antsibull_nox/sessions/build_import_check.py
- src/antsibull_nox/sessions/docs_check.py
- src/antsibull_nox/sessions/ee_check.py
- src/antsibull_nox/sessions/license_check.py
- src/antsibull_nox/sessions/lint.py
- src/antsibull_nox/sessions/utils/packages.py
More package name related cleanup.
> Improve extra deps options; deprecate shlexing of extra deps and leading dashes in package names and extra deps strings
